
import re
from datetime import datetime

def _policy(ids, policies):
    return [p for p in policies if p["id"] in ids]

def _base(intent, decision, risk, sources, reason, next_action, status, clarification=None):
    # Ticket creation is based on the actual workflow stage, not simply on
    # whether the decision text contains the word "required".
    no_ticket = {"Resolve", "Employee Action Required", "Clarification Required"}
    ticket_required = decision not in no_ticket
    if intent in {"Home-office equipment", "Software installation"}:
        ticket_required = False
    if intent == "Printer troubleshooting":
        ticket_required = False
    if intent == "Security incident":
        ticket_required = False
    if intent == "Password reset":
        ticket_required = False
    if intent == "Account lockout":
        ticket_required = True
    return {
        "intent": intent, "decision": decision, "risk": risk, "sources": sources,
        "reason": reason, "next_action": next_action, "status": status,
        "clarification": clarification, "ticket_required": ticket_required,
    }

def analyze(text, policies, tickets):
    t = text.lower().strip()
    if not t:
        return _base("Unknown", "Clarification Required", "Medium", [], 
                     "No employee request was provided.", 
                     "Ask the employee what system, device, or service is affected and what error they see.",
                     "Awaiting information", "What isn't working, and what error message are you seeing?")

    # Security: must take priority over other keyword matches
    if any(k in t for k in ["phishing", "malware", "unauthorized access", "suspicious email", "suspicious link"]):
        return _base("Security incident", "Security Escalation", "High", ["KB-09"],
                     "The request describes a suspected phishing, malware, or unauthorized-access event. The supplied policy requires immediate reporting to Security.",
                     "Report immediately to security@veridian-corp.example and do not forward the message to other employees.",
                     "Escalated to Security")

    if ("password" in t or "account" in t) and any(k in t for k in ["locked", "lockout", "failed", "wrong password", "tried"]):
        nums = re.findall(r"(\d+)\s*(?:times|attempts)", t)
        attempts = int(nums[0]) if nums else None
        if attempts is not None and attempts >= 5:
            return _base("Account lockout", "Resolve", "Low", ["KB-01"],
                         f"The employee reports {attempts} failed password attempts, which exceeds the 5-attempt lockout threshold in KB-01.",
                         "Contact IT to unlock the account manually. No approval is required.",
                         "Ready for IT unlock")
        return _base("Password reset", "Employee Action Required", "Low", ["KB-01"],
                     "Employees can reset their own password through the self-service portal.",
                     "Use the self-service password reset portal.",
                     "Employee action required")

    if "guest" in t and "wi-fi" in t or "guest" in t and "wifi" in t:
        return _base("Guest Wi-Fi", "Resolve", "Low", ["KB-07"],
                     "Guest Wi-Fi credentials can be generated by any employee from the front-desk kiosk and are valid for 24 hours.",
                     "Generate the guest credentials from the front-desk kiosk. No IT ticket is required.",
                     "Resolved")

    if "vpn" in t:
        if "contractor" in t:
            return _base("Contractor VPN access", "Approval Required", "Medium", ["KB-02"],
                         "KB-02 requires manager approval for contractor VPN access via the access request form.",
                         "Obtain manager approval through the access request form.",
                         "Pending manager approval")
        if "expired" in t or "90 days" in t:
            return _base("VPN credential renewal", "Employee Action Required", "Low", ["KB-02"],
                         "VPN credentials expire every 90 days and must be renewed by the employee.",
                         "Renew the VPN credentials.",
                         "Employee action required")
        return _base("VPN access", "Clarification Required", "Medium", ["KB-02"],
                     "KB-02 distinguishes full-time employees from contractors, and the supplied request does not establish which category applies.",
                     "Confirm whether the requester is a full-time employee or contractor.",
                     "Awaiting information", "Are you a full-time employee or a contractor?")

    if ("work from home" in t or "working from home" in t or "wfh" in t) and ("monitor" in t or "equipment" in t or "chair" in t):
        if any(k in t for k in ["approved", "manager signed", "sign-off done", "finance approved", "got approval", "already approved"]):
            return _base("Home-office equipment", "Route to IT", "Low", ["KB-10"],
                         "IT shipping after approval",
                         "KB-10 requires manager sign-off and Finance processing before IT handles shipping.",
                         "Route the equipment shipping request to IT after approval and Finance processing.",
                         "Ready for IT fulfilment")
        return _base("Home-office equipment", "Employee Action Required", "Medium", ["KB-10"],
                     "KB-10 provides the allowance for employees working remotely more than 3 days/week, subject to manager sign-off and Finance processing.",
                     "Obtain manager sign-off and Finance processing first. IT handles shipping only after approval.",
                     "Awaiting approval", "Have you received manager sign-off and completed Finance processing?")

    if "software" in t or "browser extension" in t or "extension" in t:
        if "not in" in t or "non-catalog" in t or "not in the software catalog" in t:
            return _base("Non-catalog software", "Security Escalation", "Medium", ["KB-04"],
                         "Non-catalog software requires IT Security review. The supplied policy states that review takes 3–5 business days.",
                         "Route the request for IT Security review.",
                         "Pending Security review")
        if "browser extension" in t:
            return _base("Software installation", "Human Review", "Medium", ["KB-04"],
                         "The request concerns a browser extension, but the supplied data does not establish whether it is in the approved catalog.",
                         "Confirm whether the extension is in the approved software catalog. If it is non-catalog, IT Security review is required.",
                         "Awaiting information", "Is the browser extension listed in the approved software catalog?")
        return _base("Software installation", "Clarification Required", "Medium", ["KB-04"],
                     "The supplied policy distinguishes catalog software from non-catalog software, but the request does not identify which applies.",
                     "Confirm whether the requested software is in the approved catalog.",
                     "Awaiting information", "Is the requested software in the approved catalog?")

    if "laptop" in t or "monitor" in t:
        if "flicker" in t or "flickering" in t:
            return _base("Laptop hardware issue", "Human Review", "Medium", ["KB-03", "AMP"],
                         "The employee reports a hardware issue but says they may need a fix rather than replacement. The laptop is 2 years old, so it is before the 3-year replacement eligibility threshold. The supplied policies do not provide a hardware troubleshooting procedure.",
                         "Route for hardware assessment. Do not assume replacement eligibility.",
                         "Human review")
        if "dead" in t or "won’t turn" in t or "won't turn" in t:
            return _base("Laptop hardware failure / replacement", "Human Review", "Medium", ["KB-03", "AMP"],
                         "KB-03 permits earlier replacement for verified hardware failure. The Asset Management Policy says the normal refresh cycle is 4 years and early replacement outside that cycle requires Finance sign-off in addition to IT approval. The reported failure still requires verification.",
                         "Create a hardware case for verification and route for the required IT and Finance approvals if early replacement is pursued.",
                         "Pending hardware verification")
        return _base("Laptop issue", "Clarification Required", "Medium", ["KB-03", "AMP"],
                     "Laptop replacement depends on service age and/or verified hardware failure, but the request does not provide enough information.",
                     "Ask for the laptop age and the observed issue before determining replacement handling.",
                     "Awaiting information", "How old is the laptop, and what exactly is happening with it?")

    if "printer" in t:
        return _base("Printer troubleshooting", "Employee/IT Action Required", "Low", ["KB-05"],
                     "KB-05 specifies the first troubleshooting steps: check the printer queue and restart the print spooler. If the issue persists, a ticket should be logged with the printer asset tag.",
                     "Check the printer queue and restart the print spooler. If the issue persists, log a ticket including the printer's asset tag.",
                     "Troubleshooting required")

    if "mailbox" in t or "mail" in t and "full" in t:
        return _base("Mailbox quota", "Employee Action Required", "Low", ["KB-06"],
                     "The default mailbox quota is 25GB and employees nearing quota should archive old mail. Increases above 25GB require manager approval and are capped at 50GB.",
                     "Archive old mail first. If a quota increase beyond 25GB is needed, manager approval is required and the maximum is 50GB.",
                     "Employee action required")

    if "home" in t and ("monitor" in t or "equipment" in t) or "work from home" in t:
        return _base("Home-office equipment", "Employee Action Required", "Medium", ["KB-10"],
                     "Employees working remotely more than 3 days/week are eligible for a one-time home-office equipment allowance. Manager sign-off and Finance processing are required; IT handles shipping only after approval.",
                     "Obtain manager sign-off and Finance processing. IT can handle equipment shipping once approved.",
                     "Pending manager/Finance approval")

    if "expense" in t:
        return _base("Expense software technical issue", "Route to Finance / IT support", "Medium", ["KB-08"],
                     "Access to the expense management tool is granted by Finance, not IT. IT can assist with login or technical issues once an account already exists.",
                     "If the account already exists, IT can assist with the login/technical issue. If access itself is needed, route access ownership to Finance.",
                     "Human review")

    if "admin access" in t or ("finance" in t and "server" in t and "access" in t):
        return _base("Privileged/admin access", "Human Review", "High", [],
                     "The supplied data does not contain a policy authorizing IT to grant admin access to the finance reporting server. A historical ticket shows an admin access request was rejected for missing business justification, but that ticket is historical precedent rather than a new policy.",
                     "Do not grant access automatically. Route for human review and required authorization.",
                     "Human review")

    if "not working" in t or "doesn't work" in t or "doesnt work" in t or "not working" in t:
        return _base("Unknown / ambiguous issue", "Clarification Required", "Medium", [],
                     "The request does not identify the affected system, device, or service, so selecting a policy would require guessing.",
                     "Ask for the affected system/device/service and the error message.",
                     "Awaiting information", "What isn't working, and what error message are you seeing?")

    return _base("Unknown", "Clarification Required", "Medium", [],
                  "No supplied policy can be safely selected from the information provided.",
                  "Ask the employee to describe the affected system/service and the specific issue.",
                  "Awaiting information", "Which IT system, device, or service is affected, and what problem are you seeing?")
